// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NonauthImport } from './routes/_nonauth'
import { Route as MdcImport } from './routes/_mdc'
import { Route as NonauthLogoutImport } from './routes/_nonauth/logout'
import { Route as NonauthLoginImport } from './routes/_nonauth/login'
import { Route as NonauthHomeImport } from './routes/_nonauth/home'
import { Route as MdcCollectionsImport } from './routes/_mdc/collections'
import { Route as MdcCollectionsCollectionIdImport } from './routes/_mdc/collections_.$collectionId'

// Create/Update Routes

const NonauthRoute = NonauthImport.update({
  id: '/_nonauth',
  getParentRoute: () => rootRoute,
} as any)

const MdcRoute = MdcImport.update({
  id: '/_mdc',
  getParentRoute: () => rootRoute,
} as any)

const NonauthLogoutRoute = NonauthLogoutImport.update({
  path: '/logout',
  getParentRoute: () => NonauthRoute,
} as any)

const NonauthLoginRoute = NonauthLoginImport.update({
  path: '/login',
  getParentRoute: () => NonauthRoute,
} as any)

const NonauthHomeRoute = NonauthHomeImport.update({
  path: '/home',
  getParentRoute: () => NonauthRoute,
} as any)

const MdcCollectionsRoute = MdcCollectionsImport.update({
  path: '/collections',
  getParentRoute: () => MdcRoute,
} as any)

const MdcCollectionsCollectionIdRoute = MdcCollectionsCollectionIdImport.update(
  {
    path: '/collections/$collectionId',
    getParentRoute: () => MdcRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mdc': {
      preLoaderRoute: typeof MdcImport
      parentRoute: typeof rootRoute
    }
    '/_nonauth': {
      preLoaderRoute: typeof NonauthImport
      parentRoute: typeof rootRoute
    }
    '/_mdc/collections': {
      preLoaderRoute: typeof MdcCollectionsImport
      parentRoute: typeof MdcImport
    }
    '/_nonauth/home': {
      preLoaderRoute: typeof NonauthHomeImport
      parentRoute: typeof NonauthImport
    }
    '/_nonauth/login': {
      preLoaderRoute: typeof NonauthLoginImport
      parentRoute: typeof NonauthImport
    }
    '/_nonauth/logout': {
      preLoaderRoute: typeof NonauthLogoutImport
      parentRoute: typeof NonauthImport
    }
    '/_mdc/collections/$collectionId': {
      preLoaderRoute: typeof MdcCollectionsCollectionIdImport
      parentRoute: typeof MdcImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MdcRoute.addChildren([MdcCollectionsRoute, MdcCollectionsCollectionIdRoute]),
  NonauthRoute.addChildren([
    NonauthHomeRoute,
    NonauthLoginRoute,
    NonauthLogoutRoute,
  ]),
])
